language: cpp

# The Precise container system does not support C++11, so we have to use Trusty.
sudo: required
dist: trusty

compiler:
  - gcc

# perft tests
# maybe add eval symmetry tests?
env:
  - TEST=cpw
  - TEST=hartmann

script: make
after_success: make test